server:
  port: 8882
  address: 0.0.0.0
  servlet:
    context-path: /account-service


spring:
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.1.224:3306/tcc_account?useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,log4j
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        useGlobalDataSourceStat: true
    application:
      name: account-service

#hmily:
#    tcc :
#        serializer : kryo
#        recoverDelayTime : 128
#        retryMax : 30
#        scheduledDelay : 128
#        scheduledThreadMax :  10
#        repositorySupport : db
#        tccDbConfig :
#                 driverClassName  : com.mysql.jdbc.Driver
#                 url :  jdbc:mysql://192.168.1.224:3306/tcc?useUnicode=true&amp;characterEncoding=utf8
#                 username : root
#                 password : 123456

mybatis:
  type-aliases-package: com.hmily.tcc.demo.springcloud.account.entity
  config-location: classpath:mybatis/mybatis-config.xml
#${random.int[9000,9999]}
eureka:
 client:
     serviceUrl:
       defaultZone: http://192.168.1.208:8761/eureka/
 instance:
   prefer-ip-address: true

account-service :
   ribbon.NFLoadBalancerRuleClassName : com.netflix.loadbalancer.RandomRule

logging:
    level:
        root: error
        org.springframework.web: info
        org.apache.ibatis: info
        com.hmily.tcc.bonuspoint: debug
        com.hmily.tcc.lottery: debug
        com.hmily.tcc: debug
        io.netty: info
    path: "./logs"

